### ISSUE TITLE
Unable to set up Pycharm development environment.

### ISSUE THREAD

**Issue by karandesai-96** [opencog/opencog-to-minecraft#20]
Pycharm is an IDE for python development, by Jetbrains Community and is used by many developers nowadays. But there are a lot of **ImportErrors** (rospy, roslib as well as minecraft_bot.<anything>).

**Comment by karandesai-96** [comment]
From command line, everything is fine, but Pycharm identifies any directory as a module containing submodules is by its `__init__.py` files. Proper `__init__.py` files are required in each directory, to resolve ImportErrors regarding minecraft_bot.<anything>. I am working upon it for now.

**Comment by AmeBel** [comment]
fixed by https://github.com/opencog/opencog-to-minecraft/pull/22

**Comment by karandesai-96** [comment]
This issue needs to be **re-opened**, there is a small bug which escaped out the first time.

The bug description (happens in Pycharm and other IDEs) :
* If `import minecraft_bot` is done, only the modules just inside minecraft_bot can be accessed. This means, for example, to use a class from `actionsgen.py`, we will have to do :

``` 
from minecraft_bot.src.actionsgen import ClientMover
client_mover = ClientMover() 
```

and it **doesn't** work by:

```
 import minecraft_bot
client_mover = minecraft_bot.src.actionsgen.ClientMover() 
```

**Comment by karandesai-96** [comment]
The reason due to which this issue was re=opened was a small bug which went unnoticed for the first time. As PR #27 has been merged to master, this issue is fit to be closed.
